"""Calculus (AP Calculus AB / BC) subject catalog."""

SUBJECT = {
    "id": "calculus",
    "title": "Calculus",
    "subtitle": "AB / BC",
    "symbol": "∫",
    "order": 1,
    "unitChips": {
        "1": "Limits",
        "2": "Derivatives",
        "3": "Inverse",
        "6": "Integrals",
        "7": "DiffEQ",
        "8": "Apps of ∫",
        "9": "Para / Polar",
        "10": "Series",
    },
    "visualizers": [
        {
            "id": "limit",
            "unit": 1,
            "unitTitle": "Limits & Continuity",
            "title": "Limits",
            "subtitle": "How close y must stay to L (ε), and the matching x-window around a (δ)",
            "symbol": "εδ",
            "path": "ui/limit/index.html",
        },
        {
            "id": "derivatives",
            "unit": 2,
            "unitTitle": "Differentiation Fundamentals",
            "title": "Derivatives",
            "subtitle": "Animate tangent slope, first derivative, and second-derivative concavity",
            "symbol": "f′",
            "path": "ui/derivatives/index.html",
        },
        {
            "id": "inverse",
            "unit": 3,
            "unitTitle": "Composite, Implicit & Inverse Functions",
            "title": "Inverse Visualizer",
            "subtitle": "Animate f(x), f⁻¹(x), and derivative relationships on a shared view",
            "symbol": "f⁻¹",
            "path": "ui/inverse/index.html",
        },
        {
            "id": "riemann",
            "unit": 6,
            "unitTitle": "Integration & Accumulation",
            "title": "Riemann Sums",
            "subtitle": "Compare left/right/mid/trapezoid sums against the definite integral",
            "symbol": "∫",
            "path": "ui/riemann/index.html",
        },
        {
            "id": "slope_field",
            "unit": 7,
            "unitTitle": "Differential Equations",
            "title": "Slope Fields",
            "subtitle": "Draw y′ = f(x, y), drag an initial condition, and compare Euler, midpoint, and RK4",
            "symbol": "y′",
            "path": "ui/slope_field/index.html",
            "beta": True,
        },
        {
            "id": "volume_rotation",
            "unit": 8,
            "unitTitle": "Applications of Integration",
            "title": "Volume Rotation",
            "subtitle": "Rotate bounded regions around an axis to visualize solids of revolution",
            "symbol": "⟳V",
            "path": "ui/volume_rotation/index.html",
        },
        {
            "id": "arc_length",
            "unit": 8,
            "unitTitle": "Applications of Integration",
            "title": "Arc Length",
            "subtitle": "Chords of f(x) approaching ∫ √(1 + [f′(x)]²) dx",
            "symbol": "L",
            "path": "ui/arc_length/index.html",
            "beta": True,
        },
        {
            "id": "parametric",
            "unit": 9,
            "unitTitle": "Parametric, Polar & Vector-Valued Functions",
            "title": "Parametric Curves",
            "subtitle": "Animate x(t), y(t), velocity, and motion vectors",
            "symbol": "(x,y)",
            "path": "ui/parametric/index.html",
        },
        {
            "id": "polar",
            "unit": 9,
            "unitTitle": "Parametric, Polar & Vector-Valued Functions",
            "title": "Polar Area",
            "subtitle": "Shade polar regions with sector slices and compare two curves",
            "symbol": "rθ",
            "path": "ui/polar/index.html",
        },
        {
            "id": "taylor",
            "unit": 10,
            "unitTitle": "Infinite Sequences & Series",
            "title": "Taylor Series",
            "subtitle": "Animated polynomial approximations around a center point",
            "symbol": "∑",
            "path": "ui/taylor/index.html",
        },
    ],
}
